### ISSUE TITLE
java.io.IOException: No space left on device

### ISSUE THREAD

**Issue by tigerich** [sonatype/docker-nexus#43]
with mounted volume from host, it shows "java.io.IOException: No space left on device" error when running indexing to sync the remote index with local one.

**Comment by DarthHater** [comment]
Hi there, we tried to replicate this internally and we were unsuccessful. Mind sharing your exact steps to reproduce?

**Comment by crnlmchina** [comment]
I also met the problem, the full stack trace below
```
2018-04-08 08:17:02,218+0000 WARN  [pxpool-1-thread-1] admin org.sonatype.scheduling.DefaultScheduledTask - Exception in call method of scheduled task Internal
java.io.IOException: No space left on device
        at java.io.RandomAccessFile.writeBytes(Native Method)
        at java.io.RandomAccessFile.write(RandomAccessFile.java:525)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.flushBuffer(FSDirectory.java:448)
        at org.apache.lucene.store.BufferedIndexOutput.flushBuffer(BufferedIndexOutput.java:99)
        at org.apache.lucene.store.BufferedIndexOutput.flush(BufferedIndexOutput.java:88)
        at org.apache.lucene.store.BufferedIndexOutput.writeBytes(BufferedIndexOutput.java:77)
        at org.apache.lucene.store.DataOutput.writeBytes(DataOutput.java:43)
        at org.apache.lucene.store.RAMOutputStream.writeTo(RAMOutputStream.java:65)
        at org.apache.lucene.index.FieldsWriter.flushDocument(FieldsWriter.java:116)
        at org.apache.lucene.index.StoredFieldsWriter.finishDocument(StoredFieldsWriter.java:112)
        at org.apache.lucene.index.StoredFieldsWriter$PerDoc.finish(StoredFieldsWriter.java:151)
        at org.apache.lucene.index.DocumentsWriter$WaitQueue.writeDocument(DocumentsWriter.java:1404)
        at org.apache.lucene.index.DocumentsWriter$WaitQueue.add(DocumentsWriter.java:1424)
        at org.apache.lucene.index.DocumentsWriter.finishDocument(DocumentsWriter.java:1043)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:772)
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:2060)
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:2034)
        at org.apache.maven.index.updater.IndexDataReader.readIndex(IndexDataReader.java:92)
        at org.apache.maven.index.updater.DefaultIndexUpdater.unpackIndexData(DefaultIndexUpdater.java:515)
        at org.apache.maven.index.updater.DefaultIndexUpdater.loadIndexDirectory(DefaultIndexUpdater.java:203)
        at org.apache.maven.index.updater.DefaultIndexUpdater.access$300(DefaultIndexUpdater.java:76)
        at org.apache.maven.index.updater.DefaultIndexUpdater$LuceneIndexAdaptor.setIndexFile(DefaultIndexUpdater.java:648)
        at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:877)
        at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:159)
        at org.sonatype.nexus.index.DefaultIndexerManager.updateRemoteIndex(DefaultIndexerManager.java:1291)
        at org.sonatype.nexus.index.DefaultIndexerManager.access$1100(DefaultIndexerManager.java:188)
        at org.sonatype.nexus.index.DefaultIndexerManager$IndexUpdateRunnable.run(DefaultIndexerManager.java:1060)
        at org.sonatype.nexus.index.DefaultIndexerManager.temporary(DefaultIndexerManager.java:2358)
        at org.sonatype.nexus.index.DefaultIndexerManager.reindexRepository(DefaultIndexerManager.java:1022)
        at org.sonatype.nexus.index.DefaultIndexerManager.reindexRepository(DefaultIndexerManager.java:961)
        at org.sonatype.nexus.index.DefaultIndexerManager.reindexRepository(DefaultIndexerManager.java:938)
        at org.sonatype.nexus.index.tasks.ReindexTaskHandlerLegacy.reindexRepository(ReindexTaskHandlerLegacy.java:61)
        at org.sonatype.nexus.index.tasks.AbstractIndexerTask.doRun(AbstractIndexerTask.java:68)
        at org.sonatype.nexus.scheduling.AbstractNexusTask.call(AbstractNexusTask.java:163)
        at org.sonatype.scheduling.DefaultScheduledTask.call(DefaultScheduledTask.java:418)
        at org.sonatype.nexus.threads.MDCAwareCallable.call(MDCAwareCallable.java:44)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

while I still have enough disk space
```
Filesystem      1K-blocks     Used  Available Use% Mounted on
/dev/sda2        51474912 21032432   27804656  44% /
devtmpfs         20468580        0   20468580   0% /dev
tmpfs            20478140        0   20478140   0% /dev/shm
tmpfs            20478140   107776   20370364   1% /run
tmpfs            20478140        0   20478140   0% /sys/fs/cgroup
/dev/sda1          194235   134314      45585  75% /boot
/dev/sda4      1849221436 10356120 1744906816   1% /data
```

**Comment by kylegoetz** [comment]
I have also just run into this:

```
2021-07-30 23:20:18,167+0000 INFO  [elasticsearch[56B9BB40-7ECDAB09-8F15C24D-136FD676-EABF613B][scheduler][T#1]] *SYSTEM org.elasticsearch.monitor.jvm - [56B9BB40-7ECDAB09-8F15C24D-136FD676-EABF613B] [gc][young][16020][14] duration [973ms], collections [1]/[1.1s], total [973ms]/[2.8s], memory [876.9mb]->[160.3mb]/[2.5gb], all_pools {[young] [723.9mb]->[2.4mb]/[729.5mb]}{[survivor] [5.2mb]->[10.2mb]/[87mb]}{[old] [147.6mb]->[147.6mb]/[1.7gb]}
2021-07-31 19:48:02,849+0000 ERROR [OrientDB WAL Flush Task (component)] *SYSTEM com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV2$FlushTask - Error during WAL background flush
java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:66)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:89)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:772)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:758)
	at com.orientechnologies.common.io.OIOUtils.writeByteBuffer(OIOUtils.java:412)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV2.flushPage(OLogSegmentV2.java:334)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV2.access$900(OLogSegmentV2.java:38)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV2$FlushTask.commitLog(OLogSegmentV2.java:267)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV2$FlushTask.run(OLogSegmentV2.java:124)
	at com.orientechnologies.common.concur.executors.SubExecutorService$RunnableTask.run(SubExecutorService.java:296)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

But I have 1 TB of space on my disk, 200GB allocated to Docker, just ran the command to remove all docker containers that aren't running, Docker now says 0 GB are being used, and I have about 300 GB of free space on my local machine.

**Comment by kylegoetz** [comment]
If it helps anyone, I had this problem and increased the amount of disk space given to Docker and restarted docker and then restarted my containers and the problem went away.
