### ISSUE TITLE
Container stops immediately after start with "Bad temp directory"

### ISSUE THREAD

**Issue by thogen** [sonatype/docker-nexus#73]
$ docker logs -f nexus
2018-04-11 06:12:10,355+0000 INFO  [jetty-main-1]  org.sonatype.nexus.bootstrap.jetty.JettyServer - Running
2018-04-11 06:12:10,356+0000 ERROR [main] *SYSTEM org.sonatype.nexus.bootstrap.jetty.JettyServer - Start failed
java.lang.IllegalArgumentException: Bad temp directory: /tmp/JettyContext5630915593536410496
	at org.eclipse.jetty.webapp.WebAppContext.setTempDirectory(WebAppContext.java:1119)
	at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:326)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:68)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:457)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:493)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.sonatype.nexus.bootstrap.jetty.JettyServer$JettyMainThread.run(JettyServer.java:247)
Exception in thread "main" java.lang.IllegalArgumentException: Bad temp directory: /tmp/JettyContext5630915593536410496
	at org.eclipse.jetty.webapp.WebAppContext.setTempDirectory(WebAppContext.java:1119)
	at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:326)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:68)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:457)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:493)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.sonatype.nexus.bootstrap.jetty.JettyServer$JettyMainThread.run(JettyServer.java:247)

**Comment by thogen** [comment]
Solution: In docker -> preferences -> Deamon 
   switch off "Experimental features"
